In [50]:
import pandas as pd
import matplotlib.pyplot as plt
import duckdb

In [51]:
df = pd.read_csv("../data/interim/master_cleaned.csv")
df["date"] = pd.to_datetime(df["date"])

df = df.sort_values(["coin_id", "date"])

df["price_index"] = (
    df.groupby("coin_id")["price"]
    .transform(lambda x: x / x.iloc[0] * 100)
)

df.head()

,date,coin_id,price,volume,market_cap,daily_return_pct,price_7d_ma,volume_7d_ma,price_index
0,2025-04-04,bitcoin,83163.987574,3.659446e+10,1.652537e+12,NaN,NaN,NaN,100.000000
1,2025-04-05,bitcoin,83852.007654,3.564729e+10,1.664235e+12,0.827305,NaN,NaN,100.827305
2,2025-04-06,bitcoin,83595.885502,1.491040e+10,1.656020e+12,-0.305445,NaN,NaN,100.519333
3,2025-04-07,bitcoin,78211.483582,3.614038e+10,1.555325e+12,-6.440989,NaN,NaN,94.044894
4,2025-04-08,bitcoin,79179.292268,8.290975e+10,1.581408e+12,1.237425,NaN,NaN,95.208629

In [38]:
df = pd.read_csv("../data/interim/master_cleaned.csv")
df["date"] = pd.to_datetime(df["date"])

 ## EDA 1 
 - Volitilaty: Mesauring the how the prise sways daily.
High Volitilaty = High Risk

In [53]:
# EDA 1
# Standard deviation of daily returns as a measure of volatility

vol = (
    df.groupby("coin_id")["daily_return_pct"]
    .std()
    .reset_index()
    .sort_values("daily_return_pct", ascending=False)
    .reset_index(drop=True)
)

vol.index = vol.index + 1
vol

          coin_id  daily_return_pct
1      dogwifcoin          6.726459
2           floki          5.820928
3  official-trump          5.326817
4         bitcoin          2.308453

## EDA 2 
### Average return 

- This EDA shows the average daily return on all 3 meme coins and also for Bitcoin. We can see that the meme coins may generate a highrt return from a daily perspectiv, but they also come with fastly more instabillity.

In [41]:
avg_return = (
    df.groupby("coin_id")["daily_return_pct"]
    .mean()
    .reset_index()
    .sort_values("daily_return_pct", ascending=False)
    .reset_index(drop=True)
)
avg_return.index = avg_return.index + 1
avg_return

          coin_id  daily_return_pct
1      dogwifcoin          0.020092
2           floki         -0.024676
3         bitcoin         -0.033072
4  official-trump         -0.191905

## EDA 3
### Maximum Drawdown

This EDA lets us look and get more insights into how much each coin has dropped down from its peak (largest loss).

This further more indicates the instability and shows us the other side of the "coin"

In [42]:
# EDA 3 
df = df.sort_values(["coin_id", "date"]).copy()

df["cum_max"] = df.groupby("coin_id")["price"].cummax() 
df["drawdown"] = (df["price"] - df["cum_max"]) / df["cum_max"]

drawdown_smry = (
    df.groupby("coin_id")["drawdown"]
    .min()
    .reset_index()
    .sort_values("drawdown", ascending=True)
)
drawdown_smry.index = drawdown_smry.index + 1
drawdown_smry

          coin_id  drawdown
2      dogwifcoin -0.871398
3           floki -0.824865
4  official-trump -0.819478
1         bitcoin -0.496258